// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1It4I4ZKHLrPlgBNW9mtUlYfBWt1UFdU',
    appId: '1:724007992115:web:52fb04e9b98ee8bf0adc46',
    messagingSenderId: '724007992115',
    projectId: 'chat-app-b06bb',
    authDomain: 'chat-app-b06bb.firebaseapp.com',
    storageBucket: 'chat-app-b06bb.firebasestorage.app',
    measurementId: 'G-KSLM4YD8VB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYu71rMC1EXCK47-8NSVFNttJ8j4VC0p8',
    appId: '1:724007992115:android:3fe10fb4d4079a350adc46',
    messagingSenderId: '724007992115',
    projectId: 'chat-app-b06bb',
    storageBucket: 'chat-app-b06bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3crDuRMejFeld1NV1kXt1BtDYiBQH7cM',
    appId: '1:724007992115:ios:93274c62e442d2d50adc46',
    messagingSenderId: '724007992115',
    projectId: 'chat-app-b06bb',
    storageBucket: 'chat-app-b06bb.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3crDuRMejFeld1NV1kXt1BtDYiBQH7cM',
    appId: '1:724007992115:ios:93274c62e442d2d50adc46',
    messagingSenderId: '724007992115',
    projectId: 'chat-app-b06bb',
    storageBucket: 'chat-app-b06bb.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1It4I4ZKHLrPlgBNW9mtUlYfBWt1UFdU',
    appId: '1:724007992115:web:5464df3a62a695e00adc46',
    messagingSenderId: '724007992115',
    projectId: 'chat-app-b06bb',
    authDomain: 'chat-app-b06bb.firebaseapp.com',
    storageBucket: 'chat-app-b06bb.firebasestorage.app',
    measurementId: 'G-LGVS092PX2',
  );
}
